# react Error Boundaries(错误边界)

## 定义

react 中的错误边界就是用来捕捉错误的代码。因为在 react 中，如果一个错误发生错误，就会想它的父级组件抛出错误，然后卸载自己。如果一直到根组件都不能处理错误，那么整个组件树就会被卸载，导致的页面效果就是白屏报错。而错误边界就是这样一个组件，该组件会捕获到渲染期间子组件发生的错误，并有能力阻止错误继续传播，防止组件树卸载，导致页面白屏。

错误边界在渲染期间、生命周期方法和整个组件树的构造函数中捕获错误。

## 编写

1. 使用生命周期函数`getDerivedStateFromError`

   1. 静态函数
   1. 运行时间点：渲染子组件的过程中，发生错误之后，在更新页面之前
   1. 注意：只有子组件发生错误，才会运行函数
   1. 该函数返回一个对象，React 会将该对象的属性覆盖掉当前组件的 state
   1. 参数：错误对象
   1. 通常，该函数用于改变状态

```javascript
import React, { PureComponent } from "react";
import ErrorPage from "./ErrorPage";

export default class ErrorBound extends PureComponent {
  constructor(props) {
    super(props);
    this.state = {
      hasError: false,
    };
  }

  static getDerivedStateFromError(error) {
    // 返回值会更新当前组件的state
    return { hasError: true };
  }

  render() {
    if (this.state.hasError) {
      return <ErrorPage />;
    }
    return this.props.children;
  }
}
```

2. 编写生命周期函数`componentDidCatch`

   1. 实例方法
   2. 运行时间点：渲染子组件的过程中，发生错误，更新页面之后，由于其运行时间点比较靠后，因此不太会在该函数中改变状态
   3. 通常，该函数用于记录错误消息

```javascript
import React, { PureComponent } from "react";
import ErrorPage from "./ErrorPage";

export default class ErrorBound extends PureComponent {
  constructor(props) {
    super(props);
    this.state = {
      hasError: false,
    };
  }

  componentDidCatch(error, errorInfo) {
    // 1. 错误信息（error）
    // 2. 错误堆栈（errorInfo）
    console.log(errorInof);
    this.setState({
      hasError: true,
    });
  }

  render() {
    if (this.state.hasError) {
      return <ErrorPage />;
    }
    return this.props.children;
  }
}
```

- `static getDerivedStateFromError`：在出错后有机会修改`state`触发最后一次错误`fallback`的渲染
- `componentDidCatch`：用于出错时副作用代码，比如错误上报等

注：如果一个错误边界无法渲染错误信息，则错误会冒泡至最近的上层错误边界，这也类似于 JavaScript 的 catch 的工作机制

## 错误边界的粒度

- 可以将其包装在最顶层的路由组件中，并为用户展示一个`404`的错误信息页面
- 也可以将单独的组件包装在错误边界，从而保护其它组件不会崩溃
